export const DEFAULT_SETTINGS = {
  theme: 'system',
  transparency: 0.78,
  accent: '#7c8cff',
  newTabBackground: 'aurora',
  searchEngine: 'duckduckgo',
  homepage: 'https://www.startpage.com',
  startupBehavior: 'newtab',
  askBeforeDownload: true,
  developerTools: false,
  hardwareAcceleration: true,
  downloadDirectory: '',
  onboardingCompleted: false,
  defaultBrowserPrompted: false,
  defaultBrowserRequested: false,
  performanceMode: 'balanced',
  backgroundThrottling: true,
  suspendBackgroundTabs: false,
  reducedMotion: false,
  clearOnExit: false,
  clearCookiesOnExit: true,
  clearCacheOnExit: true,
  clearHistoryOnExit: true,
  restoreSession: true,
  customSearchEngines: [],
  globalHotkeyEnabled: false,
  globalHotkey: 'Control+Shift+Space',
  readerFontSize: 18,
  readerLineHeight: 1.7,
};

export const SIDEBAR_VIEWS = [
  { id: 'bookmarks', label: 'Bookmarks' },
  { id: 'history', label: 'History' },
  { id: 'downloads', label: 'Downloads' },
  { id: 'reading', label: 'Reading list' },
  { id: 'passwords', label: 'Passwords' },
  { id: 'tabs', label: 'Tabs' },
];
