// Signing and verifying the update manifest.
//
// A code-signing certificate proves who built a file. It does not prove who put
// it on the server. If the bucket that hosts the update feed were writable by
// anyone, or the response were altered in transit, a correctly signed installer
// would still be replaced by a different one, and the updater would download it
// because the manifest said so.
//
// Signing the manifest closes that. The manifest names the file, its size and
// its SHA-512; the signature covers the manifest; the public key ships inside
// the application. An altered manifest fails the signature check before the
// updater looks at any URL, so a substituted download never starts.
//
// Ed25519 is used because verification needs no certificate authority, the
// signature is 64 bytes, and the key can live in the repository's history only
// as something that is never the private half.

const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');

const ALGORITHM = 'ed25519';
// An Ed25519 public key is 32 bytes and its signatures are 64. They are not the
// same length, and using the key length to check a signature rejects every
// valid one.
const KEY_BYTES = 32;
const SIGNATURE_BYTES = 64;
const SIGNATURE_HEADER = '# novaris-signature:';
const KEY_HEADER = '# novaris-public-key:';

function generateKeyPair() {
  const { publicKey, privateKey } = crypto.generateKeyPairSync(ALGORITHM);
  return {
    publicKeyPem: publicKey.export({ type: 'spki', format: 'pem' }).toString(),
    privateKeyPem: privateKey.export({ type: 'pkcs8', format: 'pem' }).toString(),
  };
}

/**
 * Decodes a signature, insisting on the canonical encoding.
 *
 * Node's base64 decoder silently skips characters it does not recognise, so
 * "!!w0QCM..." decodes to exactly the same bytes as "w0QCM..." and a manifest
 * with junk in its signature verifies. That cannot forge anything, since the
 * attacker would need the real signature already, but it means several different
 * texts are accepted for one manifest, which breaks the idea that a manifest has
 * one form. Re-encoding and comparing is what makes the accepted set canonical.
 */
function decodeSignatureStrict(signatureBase64) {
  const text = String(signatureBase64 || '').trim();
  if (!text) return null;
  let bytes;
  try {
    bytes = Buffer.from(text, 'base64');
  } catch {
    return null;
  }
  if (bytes.length !== SIGNATURE_BYTES) return null;
  if (bytes.toString('base64') !== text) return null;
  return bytes;
}

function sign(value, privateKeyPem) {
  const key = crypto.createPrivateKey(privateKeyPem);
  if (key.asymmetricKeyType !== ALGORITHM) {
    throw new Error(`Expected an ${ALGORITHM} key, got ${key.asymmetricKeyType}`);
  }
  return crypto.sign(null, Buffer.from(String(value), 'utf8'), key).toString('base64');
}

function verify(value, signatureBase64, publicKeyPem) {
  const bytes = decodeSignatureStrict(signatureBase64);
  if (!bytes) return false;
  try {
    const key = crypto.createPublicKey(publicKeyPem);
    if (key.asymmetricKeyType !== ALGORITHM) return false;
    return crypto.verify(null, Buffer.from(String(value), 'utf8'), key, bytes);
  } catch {
    // A malformed key or signature is a failure, never an exception to swallow.
    return false;
  }
}

/**
 * The canonical unsigned form of a manifest: no signature line, no leading or
 * trailing blank line.
 *
 * It has to be idempotent, because it is applied twice: once over the manifest
 * to produce the bytes that are signed, and once over the signed manifest to
 * recover those same bytes. An earlier version only stripped trailing
 * whitespace, so the blank line between the signature header and the body came
 * back as part of the body and every signature failed to verify.
 *
 * Trailing blank lines carry no meaning in the manifest format, so removing them
 * is safe.
 */
function unsignedBody(manifestText) {
  const lines = String(manifestText)
    .split(/\r?\n/)
    .filter((line) => !line.startsWith(SIGNATURE_HEADER));
  while (lines.length && lines[0].trim() === '') lines.shift();
  while (lines.length && lines[lines.length - 1].trim() === '') lines.pop();
  return lines.join('\n');
}

/**
 * Signs a manifest, replacing any previous signature.
 *
 * Deliberately a whole-file signature over the YAML text rather than a
 * signature over a parsed subset. A manifest is generated by the build and read
 * by one parser, so a partial signature would only create a way to change a
 * field nobody thought to include.
 */
function signManifest(manifestText, privateKeyPem) {
  const body = unsignedBody(manifestText);
  const signature = sign(body, privateKeyPem);
  // A single newline after the header, so that stripping the header leaves
  // exactly the bytes that were signed.
  return `${SIGNATURE_HEADER} ${ALGORITHM} ${signature}\n${body}\n`;
}

function readSignature(manifestText) {
  for (const line of String(manifestText).split(/\r?\n/)) {
    if (!line.startsWith(SIGNATURE_HEADER)) continue;
    // "<algorithm> <signature>". The first field is the algorithm, so it must
    // not be skipped: doing so reads the signature as the algorithm and the
    // signature as undefined, and every signed manifest then reports as unsigned.
    const parts = line.slice(SIGNATURE_HEADER.length).trim().split(/\s+/);
    const [algorithm, signature] = parts;
    if (algorithm !== ALGORITHM || !signature) return null;
    return signature;
  }
  return null;
}

/**
 * The check the updater runs before it will act on a manifest.
 *
 * Returns { ok, reason }. A missing signature is a failure, not a pass: an
 * unsigned manifest is exactly the thing this is meant to catch, and treating
 * its absence as acceptable would make the whole mechanism optional.
 */
function verifyManifest(manifestText, publicKeyPem) {
  const signature = readSignature(manifestText);
  if (!signature) {
    return { ok: false, reason: 'The update manifest carries no signature.' };
  }
  const body = unsignedBody(manifestText);
  if (!verify(body, signature, publicKeyPem)) {
    return { ok: false, reason: 'The update manifest signature does not match the bundled public key.' };
  }
  return { ok: true, reason: '' };
}

/** The public half, written as a file the application bundles. */
function writePublicKey(targetPath, publicKeyPem) {
  fs.mkdirSync(path.dirname(targetPath), { recursive: true });
  fs.writeFileSync(targetPath, `${KEY_HEADER} ${ALGORITHM}\n${publicKeyPem}`, 'utf8');
  return targetPath;
}

function readPublicKey(sourcePath) {
  const text = fs.readFileSync(sourcePath, 'utf8')
    .split(/\r?\n/)
    .filter((line) => !line.startsWith(KEY_HEADER))
    .join('\n')
    .trim();
  return text;
}

module.exports = {
  ALGORITHM,
  KEY_BYTES,
  SIGNATURE_HEADER,
  SIGNATURE_BYTES,
  decodeSignatureStrict,
  generateKeyPair,
  readPublicKey,
  readSignature,
  sign,
  signManifest,
  unsignedBody,
  verify,
  verifyManifest,
  writePublicKey,
};
