// Signing and verifying the update manifest.
//
// A code-signing certificate proves who built a file. It does not prove who put
// it on the server. If the bucket that hosts the update feed were writable by
// anyone, or the response were altered in transit, a correctly signed installer
// would still be replaced by a different one, and the updater would download it
// because the manifest said so.
//
// Signing the manifest closes that. The manifest names the file, its size and
// its SHA-512; the signature covers the manifest; the public key ships inside
// the application. An altered manifest fails the signature check before the
// updater looks at any URL, so a substituted download never starts.
//
// Ed25519 is used because verification needs no certificate authority, the
// signature is 64 bytes, and the key can live in the repository's history only
// as something that is never the private half.

const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');

const ALGORITHM = 'ed25519';
// An Ed25519 public key is 32 bytes and its signatures are 64. They are not the
// same length, and using the key length to check a signature rejects every
// valid one.
const KEY_BYTES = 32;
const SIGNATURE_BYTES = 64;
const SIGNATURE_HEADER = '# novaris-signature:';
const KEY_HEADER = '# novaris-public-key:';

function generateKeyPair() {
  const { publicKey, privateKey } = crypto.generateKeyPairSync(ALGORITHM);
  return {
    publicKeyPem: publicKey.export({ type: 'spki', format: 'pem' }).toString(),
    privateKeyPem: privateKey.export({ type: 'pkcs8', format: 'pem' }).toString(),
  };
}

/**
 * Decodes a signature, insisting on the canonical encoding.
 *
 * Node's base64 decoder silently skips characters it does not recognise, so
 * "!!w0QCM..." decodes to exactly the same bytes as "w0QCM..." and a manifest
 * with junk in its signature verifies. That cannot forge anything, since the
 * attacker would need the real signature already, but it means several different
 * texts are accepted for one manifest, which breaks the idea that a manifest has
 * one form. Re-encoding and comparing is what makes the accepted set canonical.
 */
function decodeSignatureStrict(signatureBase64) {
  const text = String(signatureBase64 || '').trim();
  if (!text) return null;
  let bytes;
  try {
    bytes = Buffer.from(text, 'base64');
  } catch {
    return null;
  }
  if (bytes.length !== SIGNATURE_BYTES) return null;
  if (bytes.toString('base64') !== text) return null;
  return bytes;
}

function sign(value, privateKeyPem) {
  const key = crypto.createPrivateKey(privateKeyPem);
  if (key.asymmetricKeyType !== ALGORITHM) {
    throw new Error(`Expected an ${ALGORITHM} key, got ${key.asymmetricKeyType}`);
  }
  return crypto.sign(null, Buffer.from(String(value), 'utf8'), key).toString('base64');
}

function verify(value, signatureBase64, publicKeyPem) {
  const bytes = decodeSignatureStrict(signatureBase64);
  if (!bytes) return false;
  try {
    const key = crypto.createPublicKey(publicKeyPem);
    if (key.asymmetricKeyType !== ALGORITHM) return false;
    return crypto.verify(null, Buffer.from(String(value), 'utf8'), key, bytes);
  } catch {
    // A malformed key or signature is a failure, never an exception to swallow.
    return false;
  }
}

/**
 * The canonical unsigned form of a manifest: no signature line, no leading or
 * trailing blank line.
 *
 * It has to be idempotent, because it is applied twice: once over the manifest
 * to produce the bytes that are signed, and once over the signed manifest to
 * recover those same bytes. An earlier version only stripped trailing
 * whitespace, so the blank line between the signature header and the body came
 * back as part of the body and every signature failed to verify.
 *
 * Trailing blank lines carry no meaning in the manifest format, so removing them
 * is safe.
 */
function unsignedBody(manifestText) {
  const lines = String(manifestText)
    .split(/\r?\n/)
    .filter((line) => !line.startsWith(SIGNATURE_HEADER));
  while (lines.length && lines[0].trim() === '') lines.shift();
  while (lines.length && lines[lines.length - 1].trim() === '') lines.pop();
  return lines.join('\n');
}

/**
 * Signs a manifest, replacing any previous signature.
 *
 * Deliberately a whole-file signature over the YAML text rather than a
 * signature over a parsed subset. A manifest is generated by the build and read
 * by one parser, so a partial signature would only create a way to change a
 * field nobody thought to include.
 */
function signManifest(manifestText, privateKeyPem) {
  const body = unsignedBody(manifestText);
  const signature = sign(body, privateKeyPem);
  // A single newline after the header, so that stripping the header leaves
  // exactly the bytes that were signed.
  return `${SIGNATURE_HEADER} ${ALGORITHM} ${signature}\n${body}\n`;
}

function readSignature(manifestText) {
  for (const line of String(manifestText).split(/\r?\n/)) {
    if (!line.startsWith(SIGNATURE_HEADER)) continue;
    // "<algorithm> <signature>". The first field is the algorithm, so it must
    // not be skipped: doing so reads the signature as the algorithm and the
    // signature as undefined, and every signed manifest then reports as unsigned.
    const parts = line.slice(SIGNATURE_HEADER.length).trim().split(/\s+/);
    const [algorithm, signature] = parts;
    if (algorithm !== ALGORITHM || !signature) return null;
    return signature;
  }
  return null;
}

/**
 * The check the updater runs before it will act on a manifest.
 *
 * Returns { ok, reason }. A missing signature is a failure, not a pass: an
 * unsigned manifest is exactly the thing this is meant to catch, and treating
 * its absence as acceptable would make the whole mechanism optional.
 */
function verifyManifest(manifestText, publicKeyPem) {
  const signature = readSignature(manifestText);
  if (!signature) {
    return { ok: false, reason: 'The update manifest carries no signature.' };
  }
  const body = unsignedBody(manifestText);
  if (!verify(body, signature, publicKeyPem)) {
    return { ok: false, reason: 'The update manifest signature does not match the bundled public key.' };
  }
  return { ok: true, reason: '' };
}

// The shape an update manifest has to have, checked after the signature has
// already passed.
//
// A signature only proves the manifest was published by whoever holds the key.
// It does not prove the manifest says anything sensible. A correctly signed
// manifest with no version, no digest, or a download URL pointing at plain HTTP
// would otherwise be handed straight to electron-updater, which trusts the
// metadata it is given. Publishing is restricted to the maintainer, so this is
// not the interesting threat on its own, but "signed" should not quietly mean
// "well formed" as well, and a manifest that has been truncated in transit is
// exactly the case where failing closed is right.

const VERSION_PATTERN = /^\d+(\.\d+){0,3}([-+][0-9A-Za-z.-]+)*$/;

/** A SHA-512 digest as base64: exactly 64 bytes, canonically encoded. */
function isSha512Base64(value) {
  const text = String(value || '').trim();
  if (!text) return false;
  try {
    const bytes = Buffer.from(text, 'base64');
    return bytes.length === 64 && bytes.toString('base64') === text;
  } catch {
    return false;
  }
}

/**
 * Is this somewhere an update may be downloaded from?
 *
 * A bare filename is relative and is resolved against the configured feed, which
 * is the only way the manifests are written. Anything with a scheme must be
 * HTTPS. A protocol-relative or backslash URL is refused rather than guessed at.
 */
function isAcceptableArtifactUrl(value) {
  const text = String(value || '').trim();
  if (!text) return false;
  if (/^[A-Za-z][A-Za-z0-9+.-]*:/.test(text)) return /^https:/i.test(text);
  if (text.startsWith('//')) return false;
  if (text.includes('\\')) return false;
  return true;
}

/**
 * Reads the fields that sit at the start of a line, which is what makes a field
 * top level. Indented lines are skipped, and that is what keeps the block-scalar
 * release notes out of the parse: their content is indented by definition.
 */
function readTopLevelFields(text) {
  const fields = new Map();
  for (const line of String(text).split(/\r?\n/)) {
    if (/^[ \t]/.test(line) || !line.trim()) continue;
    const match = line.match(/^([A-Za-z0-9_-]+):[ \t]*(.*)$/);
    if (match && !fields.has(match[1])) {
      fields.set(match[1], match[2].trim().replace(/^['"]|['"]$/g, ''));
    }
  }
  return fields;
}

/**
 * Reads the `files:` list and nothing else.
 *
 * Scoped to the block on purpose. Searching the whole document for `url:` would
 * find a bullet inside the release notes, and a release note that happened to
 * mention a URL would then be validated as if it were the download.
 */
function readFileEntries(text) {
  const lines = String(text).split(/\r?\n/);
  const start = lines.findIndex((line) => /^files:[ \t]*$/.test(line));
  if (start === -1) return [];

  const entries = [];
  let current = null;
  for (let i = start + 1; i < lines.length; i += 1) {
    const line = lines[i];
    if (!line.trim()) continue;
    // A line back at column zero ends the block.
    if (!/^[ \t]/.test(line)) break;
    const item = line.match(/^[ \t]*-[ \t]*([A-Za-z0-9_-]+):[ \t]*(.*)$/);
    if (item) {
      current = {};
      entries.push(current);
      current[item[1]] = item[2].trim();
      continue;
    }
    const field = line.match(/^[ \t]+([A-Za-z0-9_-]+):[ \t]*(.*)$/);
    if (field && current) current[field[1]] = field[2].trim();
  }
  return entries;
}

/**
 * Rejects a manifest that is signed but not usable.
 *
 * Returns { ok, reason }, and a refusal is always a refusal: the caller must not
 * fall back to downloading something less trustworthy than what it asked for.
 */
function validateManifestShape(manifestText) {
  const text = String(manifestText || '');
  if (!text.trim()) return { ok: false, reason: 'The update manifest is empty.' };

  const fields = readTopLevelFields(text);
  const version = fields.get('version') || '';
  if (!VERSION_PATTERN.test(version)) {
    return { ok: false, reason: 'The update manifest names no usable version.' };
  }

  const entries = readFileEntries(text);
  if (!entries.length) {
    return { ok: false, reason: 'The update manifest lists no download.' };
  }

  for (const entry of entries) {
    const url = entry.url || '';
    if (!isAcceptableArtifactUrl(url)) {
      return { ok: false, reason: `Refusing a download that is not over HTTPS: ${url.slice(0, 80)}` };
    }
    if (!isSha512Base64(entry.sha512)) {
      return { ok: false, reason: `The manifest entry for ${url.slice(0, 80)} carries no SHA-512 digest.` };
    }
    if (!Number.isFinite(Number(entry.size)) || Number(entry.size) <= 0) {
      return { ok: false, reason: `The manifest entry for ${url.slice(0, 80)} carries no size.` };
    }
  }

  // The top-level digest is the one electron-updater compares against for the
  // single-file path, so it is required as well as the per-file ones.
  if (!isSha512Base64(fields.get('sha512'))) {
    return { ok: false, reason: 'The update manifest carries no top-level SHA-512 digest.' };
  }

  return { ok: true, reason: '' };
}

/** The public half, written as a file the application bundles. */
function writePublicKey(targetPath, publicKeyPem) {
  fs.mkdirSync(path.dirname(targetPath), { recursive: true });
  fs.writeFileSync(targetPath, `${KEY_HEADER} ${ALGORITHM}\n${publicKeyPem}`, 'utf8');
  return targetPath;
}

function readPublicKey(sourcePath) {
  const text = fs.readFileSync(sourcePath, 'utf8')
    .split(/\r?\n/)
    .filter((line) => !line.startsWith(KEY_HEADER))
    .join('\n')
    .trim();
  return text;
}

module.exports = {
  ALGORITHM,
  KEY_BYTES,
  SIGNATURE_HEADER,
  SIGNATURE_BYTES,
  decodeSignatureStrict,
  generateKeyPair,
  isAcceptableArtifactUrl,
  isSha512Base64,
  readFileEntries,
  readPublicKey,
  readSignature,
  readTopLevelFields,
  sign,
  signManifest,
  unsignedBody,
  validateManifestShape,
  verify,
  verifyManifest,
  writePublicKey,
};
